Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Max: 298
Metrics/MethodLength:
  Max: 18
Style/IfUnlessModifier:
  Enabled: false
Metrics/CyclomaticComplexity: 
  Max: 9
Metrics/PerceivedComplexity:
  Max: 9