development:
  adapter: postgresql
  encoding: unicode
  database: posts_development
  pool: 5
  timeout: 5000
  username: vyacheslav
  password: vyacheslav 

test:
  adapter: postgresql
  encoding: unicode
  database: posts_test
  pool: 5
  timeout: 5000
  username: vyacheslav 
  password: vyacheslav